version: "3.8"
services:
  influxdb:
    image: influxdb
    container_name: Monitor-InfluxDB
    ports:
      - 8086:8086
    volumes:
      - /home/barry/Monitoring/InfluxDB-Grafana/influxdb/data:/var/lib/influxdb2
      - /home/barry/Monitoring/InfluxDB-Grafana/influxdb/config:/etc/influxdb2
    restart: always